# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.network "forwarded_port", guest: 9411, host: 9411
  config.vm.network "forwarded_port", guest: 15672, host: 15672
  config.vm.network "forwarded_port", guest: 8500, host: 8500

  config.vm.synced_folder "../../../../code", "/opt/code", create: true


  $installJava = <<-SHELL
    apt-get update
    apt-get install -y openjdk-11-jdk
    apt-get install maven -y
  SHELL

  $installMongo = <<-SHELL
    wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc |  apt-key add -
    echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" |  tee /etc/apt/sources.list.d/mongodb-org-4.2.list
    apt-get update
    apt-get install -y mongodb-org
    systemctl start mongod
    systemctl status mongod
  SHELL

  $installRabbit = <<-SHELL
    echo "deb http://www.rabbitmq.com/debian/ testing main"  | tee /etc/apt/sources.list.d/rabbitmq.list > /dev/null
    wget http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
    apt-key add rabbitmq-signing-key-public.asc
    apt-get update
    apt-get install rabbitmq-server -y
    service rabbitmq-server start
    rabbitmq-plugins enable rabbitmq_management
    rabbitmqctl add_user admin password
    rabbitmqctl set_user_tags admin administrator
    rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
    rabbitmqctl delete_user guest
    service rabbitmq-server restart
  SHELL

  $installZipkin = <<-SHELL
    curl -sSL https://zipkin.io/quickstart.sh | bash -s
    java -jar zipkin.jar >> zipkin.log &
  SHELL

  $installConsul = <<-SHELL
    apt-get install unzip -y
    wget https://releases.hashicorp.com/consul/1.7.1/consul_1.7.1_linux_amd64.zip
    unzip consul_1.7.1_linux_amd64.zip
    ./consul agent -dev -node machine >> consul.log &

    echo "FINISHED VAGRANT CONFIGURATION" 
  SHELL

  config.vm.provision "shell", inline: $installRabbit
  config.vm.provision "shell", inline: $installMongo
  config.vm.provision "shell", inline: $installJava
  config.vm.provision "shell", inline: $installZipkin
  config.vm.provision "shell", inline: $installConsul
end
